services:

  payment-service-app:
    image: pay:1.0
    container_name: payment-service-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  postgres:
    image: postgres:18.1
    container_name: postgres-db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: payment-db
      LC_MESSAGES: en_US.UTF-8
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
    restart: unless-stopped

volumes:
  db-data:
